apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: jenkins
spec:
  configurationAsCode:
    configurations:
    - name: jenkins-operator-user-configuration # DYNAMIC
  groovyScripts:
    configurations:
    - name: jenkins-operator-user-configuration # DYNAMIC
  jenkinsAPISettings:
    authorizationStrategy: createUser
  service:
    labels:
      app: jenkins-operator
      jenkins-cr: jenkins # DYNAMIC
    type: NodePort
    port: 8080
  master:
    disableCSRFProtection: false
    plugins:
    - name: simple-theme-plugin
      version: "0.6"
    basePlugins:
    - name: kubernetes
      version: "1.30.0"
    - name: workflow-job
      version: "2.41"
    - name: workflow-aggregator
      version: "2.6"
    - name: git
      version: "4.7.2"
    - name: job-dsl
      version: "1.77"
    - name: configuration-as-code
      version: "1.51"
    - name: kubernetes-credentials-provider
      version: "0.18-1"
    containers:
      - name: jenkins-master
        image: jenkins/jenkins:2.277.4-lts-alpine
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 12
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 100
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 80
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 1500m
            memory: 3Gi
          requests:
            cpu: "1"
            memory: 500Mi
  seedJobs:
    - id: jenkins-operator
      targets: "cicd/jobs/*.jenkins"
      description: "Jenkins Operator repository"
      repositoryBranch: master
      repositoryUrl: https://github.com/jenkinsci/kubernetes-operator.git
