apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jenkins-ing
spec:
  rules:
    -  host: jenkins-qa.blackowl.click
       http:
        paths:
          - backend:
              servicePort: 8080
            path: '/'
            pathType: Prefix
