apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./namespace.yaml
- ../../base
namePrefix: qa-
namespace: qa
patches:
- path: jenkins_ingress.yaml
  target:
    kind: Ingress
