apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./namespace.yaml
- ./jenkins-operator-user-configuration-cm.yaml
- ../../base
namePrefix: qa-
namespace: qa
patches:
- path: jenkins_ingress.yaml
  target:
    kind: Ingress
patchesJson6902:
- target:
    group: jenkins.io
    version: v1alpha2
    kind: Jenkins
    name: jenkins
  path: patch_jenkins_instance.yaml
- target:
    group: networking.k8s.io
    version: v1beta1
    kind: Ingress
    name: jenkins-ing
  path: patch_jenkins_ingress.yaml
