apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./namespace.yaml
- ../../base
namePrefix: dev-
namespace: dev
patches:
- path: jenkins_ingress.yaml
  target:
    kind: Ingress
patchesJson6902:
- target:
    group: jenkins.io
    version: v1alpha2
    kind: Jenkins
    name: jenkins
  path: patch_jenkins_instance.yaml
