apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: jenkins-test
  namespace: dev
spec:
  configurationAsCode:
    configurations: []
    secret:
      name: ""
  groovyScripts:
    configurations: []
    secret:
      name: ""
  jenkinsAPISettings:
    authorizationStrategy: createUser
  service:
    labels:
      app: jenkins-operator
      jenkins-cr: jenkins-dev
    type: NodePort
    port: 8080
    # nodePort: 8080
    # annotations:
      # alb.ingress.kubernetes.io/backend-protocol-version: HTTP2
  master:
    disableCSRFProtection: false
    plugins:
    - name: simple-theme-plugin
    basePlugins:
    - name: kubernetes
    - name: workflow-job
    - name: workflow-aggregator
    - name: git
    - name: job-dsl
    - name: configuration-as-code
    - name: kubernetes-credentials-provider
    containers:
      - name: jenkins-master
        image: jenkins/jenkins:2.277.4-lts-alpine
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 12
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 100
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 80
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 1500m
            memory: 3Gi
          requests:
            cpu: "1"
            memory: 500Mi
  seedJobs:
    - id: jenkins-operator
      targets: "cicd/jobs/*.jenkins"
      description: "Jenkins Operator repository"
      repositoryBranch: master
      repositoryUrl: https://github.com/jenkinsci/kubernetes-operator.git
